### ISSUE TITLE
Loads of build warnings: #include_next is a GCC extension

### ISSUE THREAD

**Issue by NielsKorschinsky** [micro-ROS/micro_ros_setup#238]
Hello,
This is more of a warning, I'm currently building the sample PONG application for my discovery_l475_iot1 board and I'm getting in every second line this warning. Do you know how to fix it / is there something missing? 

Edit: This output was produced by those commands:
> ros2 run micro_ros_setup configure_firmware.sh ping_pong --transport serial-usb
> ros2 run micro_ros_setup build_firmware.sh

```
/home/USER/microros/firmware/zephyrproject/zephyr/lib/libc/newlib/include/stdint.h:28:2: warning: #include_next is a GCC extension
   28 | #include_next <stdint.h>
      |  ^~~~~~~~~~~~
```

**Comment by pablogs9** [comment]
Hello, this a compiler dependant warning, telling that be careful to use #include_next for non-GCC compilers.

So, if you find a way for hiding it let us know or open a PR, we will be happy to get rid of this warning too.

I'm closing since we don't have plans on working on this. Do not hesitate to reopen if you have any other question.
